example_app/urls.py
"""URLs for the example app."""
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import PaymentView, HelcimJSPaymentView, SuccessView


app_name = 'example'

urlpatterns = [
    url(r'payment/basic/$', PaymentView.as_view(), name='payment_basic'),
    url(
        r'payment/helcim-js/$',
        HelcimJSPaymentView.as_view(),
        name='payment_helcim_js',
    ),
    url(r'complete/$', SuccessView.as_view(), name='complete'),
    url(
        r'^$',
        TemplateView.as_view(template_name='example_app/index.html'),
        name='home',
    ),
]

helcim_prj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, reverse_lazy
from django.views.generic import RedirectView
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('helcim/', include('helcim.urls')),
    path('example/', include('example_app.urls', namespace='example')),
    path('', RedirectView.as_view(permanent=False, url=reverse_lazy('example:home')),),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    # import debug_toolbar
    # urlpatterns = [
    #     url(r'^__debug__/', include(debug_toolbar.urls)),
    # ] + urlpatterns

example_app/models.py
from django.db import models

# Create your models here.

example_app/forms.py
"""Forms to test out django-helcim."""
from django import forms
from django.utils import timezone


def get_expiry_choices():
    """Generates proper tuples for month and year expiry choices."""
    month_choices = (
        ('01', '01'),
        ('02', '02'),
        ('03', '03'),
        ('04', '04'),
        ('05', '05'),
        ('06', '06'),
        ('07', '07'),
        ('08', '08'),
        ('09', '09'),
        ('10', '10'),
        ('11', '11'),
        ('12', '12'),
    )

    # Assembles years for the next 50 years (the longest likely expiry)
    now = timezone.now()
    year_start = now.year
    year_end = year_start + 50
    year_choices = (
        (str(year)[2:], str(year)[2:]) for year in range(year_start, year_end)
    )

    return month_choices, year_choices

class HiddenInputCustomName(forms.HiddenInput):
    """Custom hidden input that lets you specify the widget's name attribute.

        This widget helps streamline communication with Helcim.js,
        which is expecting various camelCase names (as opposed to the
        usual snake_case names used in python) and the fact that some
        form elements shouldn't have names.
    """

    def get_context(self, name, value, attrs):
        context = super(HiddenInputCustomName, self).get_context(
            name, value, attrs
        )
        context['widget']['name'] = context['widget']['attrs'].get('name', '')

        return context

class PaymentForm(forms.Form):
    """Form to manage Helcim API purchase call."""
    month_choices, year_choices = get_expiry_choices()

    cc_number = forms.CharField(
        label='Credit Card Number',
        max_length=16,
        min_length=13,
    )
    cc_name = forms.CharField(
        label='Cardholder Name',
        max_length=128,
    )
    cc_cvv = forms.CharField(
        label='CVV',
        max_length=4,
        min_length=3,
    )
    cc_expiry_month = forms.ChoiceField(
        choices=month_choices,
        label='Month Expiry'
    )
    cc_expiry_year = forms.ChoiceField(
        choices=year_choices,
        label='Year Expiry'
    )
    amount = forms.DecimalField(
        decimal_places=4,
        initial='0.00',
        label='Amount',
        min_value=0,
    )

class HelcimjsPaymentForm(forms.Form):
    """Form to manage Helcim API purchase call using Helcim.js.

        Fields in this form are not required because the Helcim.js
        scripts will capture the POST call and modify various details.
        This configuration will allow you to still use a Django form
        for validation and templating, while making use of the
        Helcim.js features.
    """
    month_choices, year_choices = get_expiry_choices()

    # Fields for user data entry
    django_cc_number = forms.CharField(
        label='Credit Card Number',
        max_length=16,
        min_length=13,
        required=False,
    )
    django_cc_expiry_month = forms.ChoiceField(
        choices=month_choices,
        label='Month Expiry',
        required=False,
    )
    django_cc_expiry_year = forms.ChoiceField(
        choices=year_choices,
        label='Year Expiry',
        required=False,
    )
    django_cc_cvv = forms.CharField(
        label='CVV',
        max_length=4,
        min_length=3,
        required=False,
    )
    django_cc_name = forms.CharField(
        label='Cardholder Name',
        max_length=256,
        required=False,
    )
    django_amount = forms.DecimalField(
        decimal_places=4,
        initial='0.00',
        label='Amount',
        min_value=0,
        required=False,
    )

    # Fields for Helcim.js processing
    helcim_cc_number = forms.CharField(
        max_length=16,
        min_length=13,
        required=False,
        widget=HiddenInputCustomName(
            attrs={'id': 'cardNumber', 'name': ''}
        ),
    )
    helcim_cc_expiry = forms.CharField(
        max_length=4,
        min_length=4,
        required=False,
        widget=HiddenInputCustomName(
            attrs={'id': 'cardExpiry', 'name': ''}
        ),
    )
    helcim_cc_cvv = forms.CharField(
        max_length=4,
        min_length=3,
        required=False,
        widget=HiddenInputCustomName(
            attrs={'id': 'cardCVV', 'name': ''}
        ),
    )
    helcim_cc_name = forms.CharField(
        max_length=256,
        required=False,
        widget=HiddenInputCustomName(
            attrs={'id': 'cardHolderName', 'name': ''}
        ),
    )
    helcim_amount = forms.CharField(
        initial='0.00',
        label='Amount',
        max_length=16,
        required=False,
        widget=HiddenInputCustomName(
            attrs={'id': 'amount', 'name': ''}
        ),
    )

example_app/views.py
"""Views to test out django-helcim."""
from django.contrib import messages
from django.forms import HiddenInput
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from helcim.exceptions import ProcessingError, PaymentError
from helcim.gateway import Purchase, HelcimJSResponse
from helcim.mixins import HelcimJSMixin
from helcim.models import HelcimTransaction, HelcimToken

from .forms import PaymentForm, HelcimjsPaymentForm


class PaymentView(FormView):
    """This view handles a basic API purchase call.

        This view is an example of how an application that requires
        payment processing (e.g. a subscription service, an online
        store) may function. The django-helcim specific details will
        be found in the post and process_payment methods. The majority
        of the remaining methods are meant to represent a generic
        service that requires payment processing.

        The GET call will return a page for the user to enter the
        payment details.

        The POST calls use a ``process`` parameter to determine if
        a confirmation page needs to be displayed or if the payment
        should be processed. This is done because you cannot transfer
        POST data securely through a redirection.
    """
    confirmation = False
    form_class = PaymentForm
    success_url = 'example:complete'
    template_details = 'example_app/payment_details.html'
    template_confirmation = 'example_app/payment_confirmation.html'

    def get_template_names(self):
        """Returns the proper template name based on payment stage."""
        conf_templates = [self.template_confirmation]
        det_templates = [self.template_details]

        return conf_templates if self.confirmation else det_templates

    def get_success_url(self, **kwargs): # pylint: disable=arguments-differ
        """Returns the success URL."""
        return reverse_lazy(self.success_url, kwargs=kwargs)

    def get(self, request, *args, **kwargs):
        """Returns the initial payment processing form."""
        return self.render_details(request)

    def post(self, request, *args, **kwargs):
        """Handles POST requests and ensure proper handling.

            The 'back' POST argument is used to signal that the user
            wants to return the payment details page.

            The 'process' POST argument is used to determine whether
            to render a confirmation page or process a payment.
        """
        # Determine POST action and direct to proper function

        # If "back" is present, return the payment details form again
        if request.POST.get('back', None):
            kwargs['back'] = True
            self.confirmation = False
            return self.render_details(request, **kwargs)

        # Process the payment
        if request.POST.get('process', None):
            return self.process_payment(request)

        # Render the confirmation page
        return self.render_confirmation(request)

    def render_details(self, request, **kwargs):
        """Renders the payment details form.

            If an error occurred during a POST, will render the
            payment form with any relevant errors.

            If "back" is present, will navigate back to payment
            details page.
        """
        context = self.get_context_data(**kwargs)

        # If there is form data already present, use it for inital form data
        # Error is added if there are processing errors during a POST
        # "back" is added when user navigates back from confirmation view
        if 'error' in kwargs or 'back' in kwargs:
            payment_form = self.form_class(request.POST)
        else:
            payment_form = self.form_class()

        context['form'] = payment_form

        return self.render_to_response(context)

    def render_confirmation(self, request, **kwargs):
        """Renders a confirmation page before processing payment.

            If forms are invalid will return to the payment details
            view for user to correct errors.
        """
        # Retrive form details
        payment_form = self.form_class(request.POST)

        # Validate form submission
        if payment_form.is_valid():
            # Sets confirmation to True to retrieve proper template
            self.confirmation = True

            # Updates Context with updated form that hides all the
            # user input via the HiddenInput Widget (this reduces the
            # risk of the user accidentally editing payment details at
            # this stage)
            context = self.get_context_data(**kwargs)
            context['form'] = self.hide_form(payment_form)

            return self.render_to_response(context)

        # Invalid form submission - render payment details again
        kwargs['error'] = True

        return self.render_details(request, **kwargs)

    def hide_form(self, form):
        """Replaces form widgets with hidden inputs.
            Parameters:
                form (obj): A form instance.
            Returns:
                obj: The modified form instance.
        """
        for _, field in form.fields.items():
            field.widget = HiddenInput()

        return form

    def process_payment(self, request, **kwargs):
        """Moves forward with payment & subscription processing."""
        # Validate payment details again incase anything changed
        payment_form = self.form_class(request.POST)

        if payment_form.is_valid():
            # Format expiry for the Helcim API (MMYY)
            cc_expiry = '{}{}'.format(
                payment_form.cleaned_data['cc_expiry_month'],
                payment_form.cleaned_data['cc_expiry_year'],
            )

            purchase = Purchase(
                save_token=True,
                amount=payment_form.cleaned_data['amount'],
                django_user=self.request.user,
                cc_name=payment_form.cleaned_data['cc_name'],
                cc_number=payment_form.cleaned_data['cc_number'],
                cc_expiry=cc_expiry,
                cc_cvv=payment_form.cleaned_data['cc_cvv'],
            )

            transaction_success = False

            try:
                transaction, token = purchase.process()
                transaction_success = bool(transaction)
            except ValueError as error:
                messages.error(request, str(error))
            except ProcessingError as error:
                # NOTE: ProcessingErrors are usually server-side errors;
                # you would not normally display them to a user
                messages.error(request, str(error))
            except PaymentError as error:
                # Format error response; the Helcim API prepends
                # "Helcim API request failed: " to the error. We strip that
                # out here to give a better user facing error
                error_message = str(error).split('Helcim API request failed: ')

                messages.error(request, error_message[1])

            # If transaction was generated, payment was successful
            if transaction_success:
                # NOTE: you generally wouldn't want to transmit these
                # details as query parameters; this is just done to
                # simplify this sandbox example
                url = '{}?transaction_type={}&transaction={}&token={}'.format(
                    self.get_success_url(),
                    'api',
                    transaction.id,
                    token.id,
                )
                return HttpResponseRedirect(url)

        # Invalid form submission/payment - render payment details again
        kwargs['error'] = True

        return self.render_details(request, **kwargs)

class HelcimJSPaymentView(HelcimJSMixin, FormView):
    """This view handles an API purchase call with Helcim.js.

        This view is an example of how an application that requires
        payment processing (e.g. a subscription service, an online
        store) may function. The django-helcim specific details will
        be found in the post and process_payment methods. The majority
        of the remaining methods are meant to represent a generic
        service that requires payment processing.

        When making a POST call, Helcim.js will intercept the request
        and direct it to the Helcim API server directly. This prevents
        any transmission of sensitive data to your servers and reduces
        your PCI Compliance requirements. These views and templates for
        this behaviour.

        The GET call will return a page for the user to enter the
        payment details.

        When the user "submits" their payment, there is client-side
        processing to generate the Confirmation view. This will enable
        confirmation display and allow an actual POST to occur.
        Helcim.js will intercept the request at this point. If the
        request is valid, the user token and response details will be
        saved; if it is invalid, the user will be directed back to the
        payment details view to review and correct the noted error(s).
    """
    form_class = HelcimjsPaymentForm
    success_url = 'example:complete'
    template_name = 'example_app/helcimjs_payment_details.html'

    def get_success_url(self, **kwargs): # pylint: disable=arguments-differ
        """Returns the success URL."""
        return reverse_lazy(self.success_url, kwargs=kwargs)

    def post(self, request, *args, **kwargs):
        """Handles remaining processing after Helcim.js processing."""
        response = HelcimJSResponse(
            response=request.POST, save_token=True, django_user=request.user
        )

        if response.is_valid():
            # NOTE: the type of transaction made by Helcim.js is determined by

example_app/templates/example_app/base.html
<!DOCTYPE html>
<html>
<head>
  <title>
    {% block main_title %}Django Helcim Sandbox{% endblock %}
    {% block sub_title %}{% endblock %}
  </title>

  <style>
    @import url('https://fonts.googleapis.com/css?family=Roboto:100,400,700&display=swap');

    html, body {
      box-sizing: border-box;
      height: 100%;
      margin: 0;
      padding: 0;
      font-size: 16px;
    }

    body {
      background-color: rgb(240, 240, 240);
      font-family: 'Roboto', Verdana, sans-serif;
      font-size: 1.1rem;
    }

    h1 {
      font-size: 3rem;
      font-weight: 100;
    }

    .layout-grid {
      display: grid;
      grid-template-areas: "nav body";
      grid-template-columns: 300px 1fr;
      grid-template-rows: 1fr;
      height: 100%;
      width: 100%;
    }

      .layout-grid nav {
        background-color: rgb(25, 25, 25);
        color: rgb(255, 255, 255);
        padding: 2rem 1rem;
        grid-area: nav;
      }

      .layout-grid section {
        background-color: rgb(255, 255, 255);
        grid-area: body;
        margin: 1rem;
        padding: 1rem 2rem;
      }

      .layout-grid nav > span:first-child {
        font-size: 1.5rem;
        font-weight: 100;
      }

    .menu {
      box-sizing: border-box;
      font-size: 1rem;
      font-weight: 700;
      list-style: none;
      margin: 0;
      padding: 2rem 0;
    }

    .menu li {
      padding: 0.5rem 0;
    }

    .menu a {
      color: rgb(255, 255, 255);
      text-decoration: none;
    }

    .menu a:hover {
      color: rgb(150, 150, 150);
    }

    .menu li > div {
      font-size: 1.1rem;
      font-weight: 100;
      margin: 1rem 0 0 0;
    }

    .messages {
      display: block;
      list-style: none;
      margin: 0;
      padding: 0;
    }

      .messages li {
        border-left: 4px solid black;
        margin: 0.25rem 0;
        padding: 0.25rem 0 0.25rem 0.5rem;
      }

        .messages li.success {
          border-left: 4px solid rgb(0, 77, 0);
          color: rgb(0, 77, 0);
        }

        .messages li.warning, .messages li.error {
          border-left: 4px solid rgb(179, 0, 0);
          color: rgb(179, 0, 0);
        }

    .field {
      display: block;
      padding: 0.25rem 0;
    }

    .field > label, .field > span.label {
      display: block;
      font-size: 0.9rem;
      font-weight: 700;
      padding: 0.25rem 0;
    }

    .field .errorlist {
      color:rgb(179, 0, 0);
      display: block;
      font-size: 0.875rem;
      list-style: none;
      margin: 0;
      padding: 0;
    }

      .field .errorlist li {
        padding: 0.5rem 0;
      }

    .field input {
      font-size: 1.1rem;
      width: 100%;
    }

    .field span.value {
      color: rgb(75, 75, 75);
      display: block;
      font-size: 1.2rem;
      padding: 0.5rem 0;
    }

    .field select {
      font-size: 1.1rem;
    }

    input[type=select] {
      font-size: 1.1rem;
    }

    .small-input > input {
      width: 5rem;
    }

    .medium-input > input {
      width: 10rem;
    }

    .large-input > input {
      width: 30rem;
    }

    button.submit,
    input[type=button].submit {
      background-color: rgb(240, 240, 240);
      border: 1px solid rgb(100, 100, 100);
      border-radius: 4px;
      cursor: pointer;
      font-size: 0.9rem;
      margin: 0.5rem 0;
      padding: 0.25rem 1rem;
    }

      button.submit:hover,
      input[type=button].submit:hover {
        background-color: rgb(230, 230, 230);
        border-color: rgb(25, 25, 25);
      }

    button.back {
      background-color: transparent;
      border: none;
      cursor: pointer;
      font-size: 1rem;
      font-weight: 700;
      margin-left: 1rem;
      text-decoration: underline;
    }

      button.back:hover {
        color: rgb(75, 75, 75);
      }

    .form-buttons {
      display: block;
      margin: 1rem 0;
    }

      .form-buttons form {
        display: inline-block;
      }

      .submit-another {
        background-color: rgb(240, 240, 240);
        border: 1px solid rgb(100, 100, 100);
        border-radius: 4px;
        color: inherit;
        cursor: pointer;
        font-size: 1.25rem;
        padding: 0.25rem 1rem;
        text-decoration: none;
      }

        .submit-another:hover {
          background-color: rgb(230, 230, 230);
          border-color: rgb(25, 25, 25);
        }
  </style>

  {% block extra_styles %}{% endblock %}
</head>

<body>
  <div class="layout-grid">
    <nav>
      <span>Django Helcim Sandbox</span>
      <ul class="menu">
        <li>
          <a href="{% url 'example:home' %}">Main</a>
        </li>
        <li><div>Example Workflows</div></li>
        <li>
          <a href="{% url 'example:payment_basic' %}">Basic Payment</a>
        </li>
        <li>
          <a href="{% url 'example:payment_helcim_js' %}">Helcim.js Payment</a>
        </li>
      </ul>
    </nav>
    <section>
      <h1>{% block h1 %}{% endblock %}</h1>
      <div class="content">
        {% if messages %}
          <ul class="messages">
            {% for message in messages %}
              {% if message.tags %}
                <li class="{{ message.tags }}">
                  {{ message }}
                </li>
              {% else %}
                <li>{{ message }}</li>
              {% endif %}
            {% endfor %}
          </ul>
        {% endif %}

        {% block content %}{% endblock %}
      </div>
    </section>
  </div>

  {% block scripts %}{% endblock %}
  {% block extra_scripts %}{% endblock %}
</body>
</html>

example_app/templates/example_app/complete.html
{% extends 'example_app/base.html' %}

{% block sub_title %}| Payment Complete {% endblock %}

{% block extra_styles %}
  <style>
    .instance-details,
    .instance-details tr,
    .instance-details th,
    .instance-details td {
      border-collapse: collapse;
    }
    .instance-details th, .instance-details td {
      padding: 1rem;
      text-align: left;
    }

    .instance-details tbody td {
      font-family: "Courier New", Courier, monospace;
      vertical-align: top;
    }

    .instance-details tbody td:first-child {
      font-weight: 700;
    }
    .instance-details tbody tr:nth-child(even) td {
      background-color: rgb(240, 240, 240);
    }
  </style>
{% endblock %}

{% block h1 %}Transaction Successfully Completed{% endblock %}

{% block content %}
  <h2>Transaction Instance Details</h2>
  <table class="instance-details">
    <thead>
      <tr>
        <th>Model Field</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>id</td>
        <td>{{ transaction.id }}</td>
      </tr>
      <tr>
        <td>raw_request</td>
        <td>{{ transaction.raw_request }}</td>
      </tr>
      <tr>
        <td>raw_response</td>
        <td>{{ transaction.raw_response }}</td>
      </tr>
      <tr>
        <td>transaction_success</td>
        <td>{{ transaction.transaction_success }}</td>
      </tr>
      <tr>
        <td>response_message</td>
        <td>{{ transaction.response_message }}</td>
      </tr>
      <tr>
        <td>notice</td>
        <td>{{ transaction.notice }}</td>
      </tr>
      <tr>
        <td>date_response</td>
        <td>{{ transaction.date_response }}</td>
      </tr>
      <tr>
        <td>date_created</td>
        <td>{{ transaction.date_created }}</td>
      </tr>
      <tr>
        <td>transaction_type</td>
        <td>
          {{ transaction.transaction_type }}
          - {{ transaction.get_transaction_type_display }}
        </td>
      </tr>
      <tr>
        <td>transaction_id</td>
        <td>{{ transaction.transaction_id }}</td>
      </tr>
      <tr>
        <td>amount</td>
        <td>{{ transaction.amount }}</td>
      </tr>
      <tr>
        <td>currency</td>
        <td>{{ transaction.currency }}</td>
      </tr>
      <tr>
        <td>cc_name</td>
        <td>{{ transaction.cc_name }}</td>
      </tr>
      <tr>
        <td>cc_number</td>
        <td>{{ transaction.cc_number }}</td>
      </tr>
      <tr>
        <td>cc_expiry</td>
        <td>{{ transaction.cc_expiry }}</td>
      </tr>
      <tr>
        <td>cc_type</td>
        <td>{{ transaction.cc_type }}</td>
      </tr>
      <tr>
        <td>token</td>
        <td>{{ transaction.token }}</td>
      </tr>
      <tr>
        <td>token_f4l4</td>
        <td>{{ transaction.token_f4l4 }}</td>
      </tr>
      <tr>
        <td>avs_response</td>
        <td>{{ transaction.avs_response }}</td>
      </tr>
      <tr>
        <td>cvv_response</td>
        <td>{{ transaction.cvv_response }}</td>
      </tr>
      <tr>
        <td>approval_code</td>
        <td>{{ transaction.approval_code }}</td>
      </tr>
      <tr>
        <td>order_number</td>
        <td>{{ transaction.order_number }}</td>
      </tr>
      <tr>
        <td>customer_code</td>
        <td>{{ transaction.customer_code }}</td>
      </tr>
      <tr>
        <td>django_user</td>
        <td>{{ transaction.django_user }}</td>
      </tr>
    </tbody>
  </table>

  <h2>Token Instance Details</h2>

  <table class="instance-details">
    <thead>
      <tr>
        <th>Model Field</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>id</td>
        <td>{{ token.id }}</td>
      </tr>
      <tr>
        <td>token</td>
        <td>{{ token.token }}</td>
      </tr>
      <tr>
        <td>token_f4l4</td>
        <td>{{ token.token_f4l4 }}</td>
      </tr>
      <tr>
        <td>cc_name</td>
        <td>{{ token.cc_name }}</td>
      </tr>
      <tr>
        <td>cc_expiry</td>
        <td>{{ token.cc_expiry }}</td>
      </tr>
      <tr>
        <td>cc_type</td>
        <td>{{ token.cc_type }}</td>
      </tr>
      <tr>
        <td>date_added</td>
        <td>{{ token.date_added }}</td>
      </tr>
      <tr>
        <td>customer_code</td>
        <td>{{ token.customer_code }}</td>
      </tr>
      <tr>
        <td>django_user</td>
        <td>{{ token.django_user }}</td>
      </tr>
    </tbody>
  </table>

  <div style="margin: 4rem 0 2rem 0;">
    {% if transaction_type == 'api' %}
    <a href="{% url 'example:payment_basic' %}" class="submit-another">Submit another transaction</a>
    {% else %}
      <a href="{% url 'example:payment_helcim_js' %}" class="submit-another">Submit another transaction</a>
    {% endif %}
  </div>
{% endblock %}

example_app/templates/example_app/helcimjs_payment_details.html
{% extends 'example_app/base.html' %}
{% load static %}

{% block extra_styles %}
  <style>
    #header-payment.hide {
      display: none;
    }

    #header-confirmation.hide {
      display: none;
    }

    #payment-form {
      max-width: 20rem;
    }

      #payment-form.hide {
        display: none;
      }

    #confirmation-details {
      max-width: 20rem;
    }

      #confirmation-details.hide {
        display: none;
      }
  </style>
{% endblock %}

{% block sub_title %}| Payment Details {% endblock %}

{% block h1 %}
  <span id="header-payment">Helcim.js &rsaquo; Enter Payment and Order Details</span>
  <span id="header-confirmation" class="hide">Helcim.js &rsaquo; Confirm Order and Payment Details</span>
{% endblock %}

{% block content %}
  <div id="payment-form">
    <div class="field">
      {{ form.django_cc_number.label_tag }}
      {{ form.django_cc_number }}
      <span id="django-cc-number-errors">{{ form.django_cc_number.errors }}</span>
    </div>

    <div class="field">
      {{ form.django_cc_name.label_tag }}
      {{ form.django_cc_name }}
      <span id="django-cc-name-errors">{{ form.django_cc_name.errors }}</span>
    </div>

    <div class="field small-input">
      {{ form.django_cc_cvv.label_tag }}
      {{ form.django_cc_cvv }}
      <span id="django-cc-cvv-errors">{{ form.django_cc_cvv.errors }}</span>
    </div>

    <div class="field">
      <label for="{{ form.django_cc_expiry_month.id_for_label }}">
        Expiry
      </label>
      {{ form.django_cc_expiry_month }} {{ form.django_cc_expiry_year }}
      {{ form.django_cc_expiry_month.errors }}
      <span id="django-cc-expiry-errors">{{ form.django_cc_expiry_year.errors }}</span>
    </div>

    <div class="field small-input">
      {{ form.django_amount.label_tag }}
      {{ form.django_amount }}
      <span id="django-amount-errors">{{ form.django_amount.errors }}</span>
    </div>

    <div class="form-buttons">
      <button id="proceed-to-confirmation" class="submit">Submit</button>
    </div>
  </div>

  <div id="confirmation-details" class="hide">
    <div class="field">
      <span class="label">Credit Card Number:</span>
      <span id="confirmation-cc-number" class="value"></span>
    </div>

    <div class="field">
      <span class="label">Cardholder Name:</span>
      <span id="confirmation-cc-name" class="value"></span>
    </div>

    <div class="field">
      <span class="label">Expiry:</span>
      <span  id="confirmation-cc-expiry" class="value"></span>
    </div>

    <div class="field">
      <span class="label">Amount:</span>
      <span id="confirmation-amount" class="value"></span>
    </div>

    <form action="" method="post" name="helcimForm" id="helcimForm" class="payment-form">
      <!-- This div is used to display results from Helcim.js (e.g. errors) -->
      <div id="helcimResults"></div>

      <!-- Hidden fields to allow Helcim.js to function -->
      <input type="hidden" id="token" value="{{ helcim_js.purchase.token }}">
      <input type="hidden" id="test" value="1">

      <!-- Fields to use for Helcim.js submission -->
      {{ form.helcim_cc_number }}
      {{ form.helcim_cc_expiry }}
      {{ form.helcim_cc_cvv }}
      {{ form.helcim_cc_name }}
      {{ form.helcim_amount }}

      {% csrf_token %}

      <div class="form-buttons">
        <input type="button" id="buttonProcess" class="submit" value="Submit" onclick="javascript:helcimProcess();">
        <button type="button" id="back-to-details" class="back">Back</button>
      </div>
    </form>
  </div>
{% endblock %}

{% block extra_scripts %}
  <script type="text/javascript" src="{{ helcim_js.purchase.url }}"></script>
  <script type="text/javascript" src="{% static 'example_app/helcimjs_payment_details.js' %}"></script>
{% endblock %}

example_app/templates/example_app/index.html
{% extends 'example_app/base.html' %}
{% block h1 %}Hello World!{% endblock %}

{% block content %}
  <p>
    Choose one of the example workflows from the sidebar to see how you
    can implement django-helcim into your project.
  </p>
{% endblock %}